name: Release Project
on:
  push:
    branches:
      - devel
      - master
      - test

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set release tag
      # Generate a release tag name in the format:
      # devel/YYYY-MM-DD/HHMMSS
      # Writes this out to the environment file for use downstream
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/heads/}/$(date +'%Y-%m-%d/%H%M%S')" >> $GITHUB_ENV
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install
      run: yarn install
    - name: Compile build
      run: ./compile-build.sh release.tar.gz dist
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        body: |
            Automated release
        prerelease: ${{ github.ref == 'refs/heads/test' }}
